### ISSUE TITLE
Ray casts against parallel segments return intersection

### ISSUE THREAD

**Issue by eldyer** [rustsim/ncollide#269] opened 2019-03-11 10:12 UTC
Ray casts against segments with ray direction parallel to the segment return an intersection with toi = 0.0 instead of None.

This was reported in #178 and allegedly fixed in #196 but still exists.

```
use nalgebra::{Isometry2, Point2, Vector2};
use ncollide2d::{
    query::{Ray, RayCast},
    shape::Segment,
};

#[test]
fn test_ray_parallel_to_segment() {
    let segment = Segment::new(Point2::new(1.0, 2.0), Point2::new(1.0, -2.0));
    let ray = Ray::new(Point2::new(0.0, 0.0), Vector2::new(0.0, -1.0));
    let toi = segment.toi_with_ray(&Isometry2::identity(), &ray, true);
    assert!(toi.is_none());
}
```

**Comment by sebcrozet** [comment] 2019-03-16 14:25
Thank you for reporting this. This is a regression due to the addition of a specialized ray-cast on 2D segment. This will be fixed today.

**Comment by sebcrozet** [comment] 2019-03-16 15:47
It appears that ncollide's test are not run at all by the CI. This explains why we did not see this regression coming. I will fix the CI at the same time as this issue.

**Closed** 2019-03-16 16:36 UTC
